project 'LiZhiFM.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiZhiFM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'AliyunPlayer_iOS/AliyunPlayerSDK','~> 3.4.0.1'
pod 'MJExtension'
pod 'Google-Mobile-Ads-SDK'

  # Pods for LiZhiFM

end
