project 'VideoPlayer.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoPlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
#   pod 'AliyunPlayer_iOS/AliyunPlayerSDK'
   pod 'VitamioSDK-iOS', '~> 1.0.2'


  # Pods for VideoPlayer

end
