project 'upload.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'upload' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'AFNetworking', '3.1.0'
  # Pods for upload

  target 'uploadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'uploadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
