project '原生调webView.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '原生调webView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 原生调webView
  pod 'AFNetworking'
  pod 'SDWebImage'
#pod 'PLCameraStreamingKit'
pod 'pili-librtmp'
pod 'QNNetDiag'
pod 'HappyDNS'

  target '原生调webViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
