project 'tottie.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tottie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'lottie-ios'
pod 'AFNetworking'
pod 'IQKeyboardManager'
pod 'SSZipArchive'
pod 'YHPDFImageLoader'
pod 'MobileVLCKit'

  # Pods for tottie

  target 'tottieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
