# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'  #官方仓库的地址
source 'http://git.mhace.com/ios/YHLibSpec.git'

target 'podtest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
#    pod 'YHLibSrc', '1.0.7'

  # Pods for podtest

end
