project 'App update.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App update' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'AFNetworking', '~> 3.1.0'
  # Pods for App update

  target 'App updateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'App updateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
