project 'BuglyDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuglyDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Bugly'
  # Pods for BuglyDemo

  target 'BuglyDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuglyDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
