project 'JPush.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JPush' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'JPush', '3.0.2'

  # Pods for JPush

  target 'JPushTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JPushUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
