project 'English.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'English' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AliyunPlayer_iOS/AliyunPlayerSDK'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'Google-Mobile-Ads-SDK'

  # Pods for English

end
