project '局域网传文件.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '局域网传文件' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod "GCDWebServer/WebUploader", "~> 3.0"

  # Pods for 局域网传文件

  target '局域网传文件UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
