project 'RAC.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
#    pod 'ReactiveCocoa', '~> 5.0.3'
pod "ReactiveCocoa", "~> 2.5"


  # Pods for RAC

  target 'RACTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
