project 'hanyutv.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hanyutv' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'MLeaksFinder', '~> 1.0.0'

  # Pods for hanyutv

  target 'hanyutvTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hanyutvUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
