project 'test.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'  #官方仓库的地址
source 'https://gitee.com/czljcb/DSSpecs.git'
source 'https://github.com/JaySonGD/podspec.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
#  pod 'VVPlayer’
#  pod 'YYPlayer’
  pod 'ZZLoading/AA’

  # Pods for test

end
