project 'VitamioSDK-iOS.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VitamioSDK-iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'VitamioSDK-iOS', '~> 1.0.2'

  # Pods for VitamioSDK-iOS

end
