project '36admob.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '36admob' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
#pod 'Google-Mobile-Ads-SDK'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
  # Pods for 36admob

  target '36admobTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '36admobUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
