project 'player.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'player' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AliyunPlayer_iOS/AliyunPlayerSDK'

  # Pods for player

end
