project 'liwu.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'liwu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'IQKeyboardManager'

  # Pods for liwu

  target 'liwuUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
