project '9*9.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '9*9' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Google-Mobile-Ads-SDK'

  # Pods for 9*9

end
