project 'AppIcon.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppIcon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppIcon
  pod 'AFNetworking', '~> 3.1.0'

  target 'AppIconTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppIconUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
