project 'chatRoom.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chatRoom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
# pod 'Hyphenate_CN'
   pod 'AFNetworking', '~> 3.1.0'
 

  # Pods for chatRoom

  target 'chatRoomTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chatRoomUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
