project 'Touch ID.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Touch ID' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.4'

  # Pods for Touch ID

  target 'Touch IDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Touch IDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
