project 'FreeStreamerDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FreeStreamerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'FreeStreamer'
pod 'MJExtension'
pod 'AFNetworking'
    pod 'LKDBHelper'
  # Pods for FreeStreamerDemo

  target 'FreeStreamerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FreeStreamerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
