project 'VipPlay.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VipPlay' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AXWebViewController', '~> 0.7.2'
pod 'FTPopOverMenu'
pod 'AliyunPlayer_iOS/AliyunPlayerSDK','~>3.4.0.1'
#pod 'KSYMediaPlayer_iOS/KSYMediaPlayer_vod'

  # Pods for VipPlay

end
