project 'JSPlayer.xcodeproj'

# platform :ios, '9.0'

target 'JSPlayer' do
  # use_frameworks!


  # pod 'KSYMediaPlayer_iOS/KSYMediaPlayer_vod'#, "~> 3.0.4"
  pod 'KSYMediaPlayer_iOS/KSYMediaPlayer_vod', :git => 'https://github.com/ksvc/KSYMediaPlayer_iOS.git', :tag => 'v3.0.4'

end
