project 'GPUImage.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPUImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
     pod 'GPUImage', '~> 0.1.7'


  # Pods for GPUImage

end
